### ISSUE TITLE
Elixir usage in README

### ISSUE THREAD

**Issue by andreapavoni** [zhongwencool/ecron#3]
Hi there,

congrats for this package, I like it's implementation. However, I'm an Elixir developer, and I'm struggling a bit understanding the config. Maybe I can achieve it anyway with some trial-error manual syntax conversion, however it'd be very helpful to have an example to follow/copy in README.

If someone else doesn't come before me, I'll create a PR ;-)

**Comment by zhongwencool** [comment]
Thanks for your advice！i will update it next version with more example and some awesome function send_interval send_after.  please see the latest pr for more detail~

**Comment by andreapavoni** [comment]
Cool, thanks!

**Comment by zhongwencool** [comment]
#4 
elixir examples in https://github.com/zhongwencool/ecron/tree/master/examples/titan_elixir
