### ISSUE TITLE
Please clarify typespec of ecron:add()

### ISSUE THREAD

**Issue by lud** [zhongwencool/ecron#9]
Hi, 

It seems to me that the correct usage of `ecron:add/3` is to give a tuple `{mod :: atom(), func :: atom(), args :: list(any())}` as the third argument.

But the typespec in your module uses `mfa()` which is `{atom(), atom(), byte()}` where `byte()` is used to give an arity and not a list of arguments.

So Dialyzer in angry !

**Comment by zhongwencool** [comment]
Thanks for reporting, I have fixed it on `v0.5.3` 
https://github.com/zhongwencool/ecron/pull/10

**Comment by lud** [comment]
Very nice of you :)
